### ISSUE TITLE
Best practices on how to use these templates from a configuration management perspective

### ISSUE THREAD

**Issue by marcusphi** [aws-quickstart/quickstart-atlassian-bitbucket#20]
We are in the process of migrating our on-prem solution to Bitbucket Datacenter in AWS. I wonder how to use these CloudFormation templates from a configuration management perspective.

1. Is there any support by AWS?
1. How do you recommend I do version control and configuration management of them?
    Is cloning this repo and maintaining our own version a good idea?
    If so, any suggestions on how to integrate changes from here?
    I mean not the git commands to do it, but rather whether this is sa good idea and if so, is there something we should bear in mind, e.g. are you striving to be backwards compatible?
1. When do you sync them to S3? Is it the master branch you deploy? After some testing?
    (https://aws-quickstart.s3.amazonaws.com/quickstart-atlassian-bitbucket/templates/quickstart-bitbucket-master.template and the two submodules)

**Comment by tonynv** [comment]
closing old issues
