### ISSUE TITLE
Can't connect from Bastion host to Bitbucket Node

### ISSUE THREAD

**Issue by marcusphi** [aws-quickstart/quickstart-atlassian-bitbucket#21]
Isn't the idea that you use the Bastion host as a jump host to reach the hosts in the private network such as the Bitbucket DC Nodes? But the security group of the Bitbucket DC (used by Bitbucket Nodes, FileServer and other components) does not include such an entry.

I added an entry with _allow SSH, TCP, port 22 from Bastion SecurityGroup_ to BitbucketDCStack SecurityGroup, and then I can connect from bastion to DC node.

Can you please add this change to the CloudFormation templates?

If this is not the right solution, how am I then to access the host in the private network?

**Comment by tonynv** [comment]
closing old issues
